# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('membershipapp', '0001_initial'),
        ('backofficeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetailHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('total_rent', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('discount_percent', models.CharField(max_length=20, null=True, blank=True)),
                ('extra_pre_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_hour_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_broken_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('facility_detail', models.TextField(null=True, blank=True)),
                ('total_facility_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Hall_booking_detail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_no', models.CharField(max_length=50, blank=True)),
                ('name', models.CharField(max_length=50, blank=True)),
                ('gst_no', models.CharField(max_length=20, null=True, blank=True)),
                ('from_date', models.DateField(default=django.utils.timezone.now, blank=True)),
                ('to_date', models.DateField(default=django.utils.timezone.now, blank=True)),
                ('total_rent', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('first_total_rent_for_reference', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('discounted_total_rent', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('is_discount', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('tds', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('deposit', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('deposit_status', models.IntegerField(blank=True, null=True, choices=[(0, b'Retained'), (1, b'Refund')])),
                ('is_deposit_through_cheque', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('discount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('discount_per', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('gst_tax', models.CharField(max_length=20, null=True, blank=True)),
                ('gst_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('total_payable', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('paid_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('payment_method', models.IntegerField(default=0, choices=[(0, b'Offline'), (1, b'Online')])),
                ('payment_status', models.IntegerField(default=8, choices=[(0, b'Cancelled'), (1, b'Paid'), (2, b'Online Pending'), (3, b'Offline Pending'), (4, b'Spot Booking Pending'), (5, b'MCCIA Booking Pending'), (6, b'Confirmed'), (7, b'Settled'), (8, b'Pending'), (9, b'Partial'), (10, b'Not Paid'), (11, b'Failed'), (12, b'Initiated')])),
                ('booking_status', models.IntegerField(default=8, choices=[(0, b'Cancelled'), (1, b'Paid'), (2, b'Online Pending'), (3, b'Offline Pending'), (4, b'Spot Booking Pending'), (5, b'MCCIA Booking Pending'), (6, b'Confirmed'), (7, b'Settled'), (8, b'Pending'), (9, b'Accepted'), (10, b'Rejected')])),
                ('booking_for', models.IntegerField(default=2, choices=[(0, b'Internal'), (1, b'Member'), (2, b'Non-Member')])),
                ('extra_pre_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_post_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_hour_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_broken_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('total_facility_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('total_cancellation_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('refund_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('total_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('net_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('bill_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('bill_date', models.DateTimeField(null=True, blank=True)),
                ('bill_no', models.CharField(max_length=50, null=True, blank=True)),
                ('total_services', models.CharField(max_length=20, null=True, blank=True)),
                ('shexcesspayment', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('shexcesspayment_desc', models.TextField(null=True, blank=True)),
                ('educess', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('seducess', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('invoice_total_rent', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('created_by', models.CharField(max_length=300, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_completed', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('member', models.ForeignKey(blank=True, to='membershipapp.UserDetail', null=True)),
                ('system_user_profile', models.ForeignKey(blank=True, to='backofficeapp.SystemUserProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hallbooking_company_detail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company_individual_name', models.CharField(max_length=50, blank=True)),
                ('address', models.CharField(max_length=150, blank=True)),
                ('contact_person', models.CharField(max_length=20, null=True, blank=True)),
                ('designation', models.CharField(max_length=50, blank=True)),
                ('mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_r', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_o', models.CharField(max_length=50, null=True, blank=True)),
                ('std_code', models.CharField(max_length=50, blank=True)),
                ('email', models.CharField(max_length=90, blank=True)),
                ('event_nature', models.CharField(max_length=50, blank=True)),
                ('from_date', models.DateField(default=django.utils.timezone.now, blank=True)),
                ('to_date', models.DateField(default=django.utils.timezone.now, blank=True)),
                ('total_rent', models.CharField(default=0, max_length=20, null=True, blank=True)),
                ('total_payable', models.CharField(default=0, max_length=20, null=True, blank=True)),
                ('deposit', models.CharField(default=0, max_length=20, null=True, blank=True)),
                ('gst', models.CharField(default=0, max_length=20, null=True, blank=True)),
                ('payment_method', models.CharField(default=b'Offline', max_length=20, null=True, blank=True, choices=[(0, b'Offline'), (1, b'Online')])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('member', models.ForeignKey(blank=True, to='membershipapp.UserDetail', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallBookingDepositDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('cheque_no', models.CharField(max_length=10, null=True, blank=True)),
                ('cheque_date', models.DateField(null=True, blank=True)),
                ('bank_name', models.CharField(max_length=30, null=True, blank=True)),
                ('customer_name', models.CharField(max_length=30, null=True, blank=True)),
                ('email', models.CharField(max_length=90, null=True, blank=True)),
                ('mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('date_of_return', models.DateTimeField(null=True, blank=True)),
                ('deposit_status', models.IntegerField(blank=True, null=True, choices=[(0, b'Retained'), (1, b'Refund')])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_booking', models.ForeignKey(blank=True, to='hallbookingapp.HallBooking', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallBookingDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pi_no', models.CharField(max_length=15, null=True, blank=True)),
                ('booking_detail_no', models.CharField(max_length=50, blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('company', models.CharField(max_length=200, null=True, blank=True)),
                ('contact_person', models.CharField(max_length=70, null=True, blank=True)),
                ('designation', models.CharField(max_length=50, null=True, blank=True)),
                ('mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_r', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_o', models.CharField(max_length=50, null=True, blank=True)),
                ('std_code', models.CharField(max_length=50, null=True, blank=True)),
                ('email', models.CharField(max_length=90, null=True, blank=True)),
                ('event_nature', models.CharField(max_length=50, null=True, blank=True)),
                ('booking_from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_from_date_for_reference', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_to_date_for_reference', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot', models.CharField(max_length=5, null=True, blank=True)),
                ('member_price', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('non_member_price', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('member_extra_hour_price', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('non_member_extra_hour_price', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_pre_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_hour', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_hour_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('extra_broken_detail', models.CharField(max_length=30, null=True, blank=True)),
                ('extra_broken_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('total_rent', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('first_total_rent_for_reference', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('gst_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('discount_percent', models.CharField(max_length=20, null=True, blank=True)),
                ('facility_detail', models.TextField(null=True, blank=True)),
                ('total_facility_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('is_cancelled', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('cancellation_date', models.DateField(null=True, blank=True)),
                ('cancellation_type', models.IntegerField(default=0, choices=[(0, b'User'), (1, b'MCCIA')])),
                ('cancellation_percent', models.DecimalField(default=0, null=True, max_digits=5, decimal_places=0, blank=True)),
                ('cancellation_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('cancellation_gst', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('cancellation_remark', models.CharField(max_length=100, null=True, blank=True)),
                ('booking_status', models.IntegerField(default=8, choices=[(0, b'Cancelled'), (1, b'Paid'), (2, b'Online Pending'), (3, b'Offline Pending'), (4, b'Spot Booking Pending'), (5, b'MCCIA Booking Pending'), (6, b'Confirmed'), (7, b'Settled'), (8, b'Pending'), (9, b'Accepted'), (10, b'Rejected')])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_booking', models.ForeignKey(blank=True, to='hallbookingapp.HallBooking', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallCancelPolicy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('day_range', models.CharField(max_length=10, null=True, blank=True)),
                ('charges', models.DecimalField(default=0, null=True, max_digits=4, decimal_places=0, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='HallCheckAvailability',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('booking_from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_from_time', models.TimeField(null=True, blank=True)),
                ('booking_to_time', models.TimeField(null=True, blank=True)),
                ('booking_status', models.IntegerField(default=8, choices=[(0, b'Cancelled'), (1, b'Paid'), (2, b'Online Pending'), (3, b'Offline Pending'), (4, b'Spot Booking Pending'), (5, b'MCCIA Booking Pending'), (6, b'Confirmed'), (7, b'Settled'), (8, b'Pending'), (9, b'Accepted'), (10, b'Rejected')])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_booking_detail', models.ForeignKey(blank=True, to='hallbookingapp.HallBookingDetail', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hall_name', models.CharField(max_length=75, blank=True)),
                ('longitude', models.CharField(max_length=20, null=True, blank=True)),
                ('latitude', models.CharField(max_length=20, null=True, blank=True)),
                ('capacity', models.IntegerField(default=50)),
                ('seating_style', models.CharField(max_length=20, blank=True)),
                ('facility', models.TextField(null=True, blank=True)),
                ('hall_image', models.ImageField(null=True, upload_to=b'HallImage', blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('extra_pre_hour', models.CharField(max_length=10, blank=True)),
                ('extra_hour', models.CharField(max_length=10, blank=True)),
                ('extra_member_price', models.IntegerField(default=50)),
                ('extra_nonmember_price', models.IntegerField(default=50)),
                ('booking_start_time', models.TimeField(null=True, blank=True)),
                ('booking_end_time', models.TimeField(null=True, blank=True)),
                ('hall_merge', models.CharField(max_length=100, null=True, blank=True)),
                ('is_merge', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_video', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_open_for_online', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='HallEquipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('member_charges', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('non_member_charges', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_detail', models.ForeignKey(blank=True, to='hallbookingapp.HallDetail', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallFunctioningEquipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('equipment_name', models.CharField(max_length=300)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='HallInterest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('add_location', models.CharField(max_length=100, null=True, blank=True)),
                ('hall_name', models.CharField(max_length=100, null=True, blank=True)),
                ('name', models.CharField(max_length=100, null=True, blank=True)),
                ('email', models.CharField(max_length=100, null=True, blank=True)),
                ('contact_no', models.CharField(max_length=100, null=True, blank=True)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='HallLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('location', models.CharField(max_length=100, null=True, blank=True)),
                ('terms_condition', models.CharField(max_length=100, null=True, blank=True)),
                ('hall_rent_on_holiday', models.FloatField(null=True, blank=True)),
                ('deposit_holiday_factor', models.FloatField(null=True, blank=True)),
                ('email', models.EmailField(max_length=100, null=True, blank=True)),
                ('deposit', models.FloatField(null=True, blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('meta_title', models.TextField(null=True, blank=True)),
                ('meta_keywords', models.TextField(null=True, blank=True)),
                ('meta_description', models.TextField(null=True, blank=True)),
                ('meta_keyphrases', models.TextField(null=True, blank=True)),
                ('priority', models.IntegerField(null=True, blank=True)),
                ('from_hour', models.CharField(max_length=50, null=True, blank=True)),
                ('to_hour', models.CharField(max_length=50, null=True, blank=True)),
                ('link', models.CharField(max_length=500, null=True, blank=True)),
                ('from_time', models.TimeField(max_length=50, null=True, blank=True)),
                ('to_time', models.TimeField(max_length=50, null=True, blank=True)),
                ('valid_from', models.DateTimeField(null=True, blank=True)),
                ('valid_to', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('city', models.ForeignKey(blank=True, to='adminapp.City', null=True)),
                ('contact_person1', models.ForeignKey(related_name='contact_person3', blank=True, to='backofficeapp.SystemUserProfile', null=True)),
                ('contact_person2', models.ForeignKey(related_name='contact_person4', blank=True, to='backofficeapp.SystemUserProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallPaymentDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('payment_mode', models.IntegerField(default=0, choices=[(0, b'Offline'), (1, b'Online')])),
                ('offline_payment_by', models.CharField(default=b'Cheque', max_length=20, null=True, blank=True, choices=[(0, b'Cheque'), (1, b'Cash'), (2, b'NEFT'), (3, b'Deposit')])),
                ('payable_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('paid_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('tds_amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('is_tds', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('payment_status', models.IntegerField(default=10, choices=[(0, b'Cancelled'), (1, b'Paid'), (2, b'Online Pending'), (3, b'Offline Pending'), (4, b'Spot Booking Pending'), (5, b'MCCIA Booking Pending'), (6, b'Confirmed'), (7, b'Settled'), (8, b'Pending'), (9, b'Partial'), (10, b'Not Paid'), (11, b'Failed'), (12, b'Initiated')])),
                ('payment_date', models.DateTimeField(null=True, blank=True)),
                ('cheque_no', models.CharField(max_length=10, null=True, blank=True)),
                ('cheque_date', models.DateField(null=True, blank=True)),
                ('bank_name', models.CharField(max_length=30, null=True, blank=True)),
                ('bounce_charge', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('bounce_cheque_remark', models.CharField(max_length=250, null=True, blank=True)),
                ('neft_id', models.CharField(max_length=30, null=True, blank=True)),
                ('cash_no', models.CharField(max_length=30, null=True, blank=True)),
                ('transaction_no', models.CharField(max_length=30, null=True, blank=True)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_booking', models.ForeignKey(blank=True, to='hallbookingapp.HallBooking', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallPricing',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hours', models.CharField(max_length=10, blank=True)),
                ('member_price', models.IntegerField(default=50)),
                ('nonmember_price', models.IntegerField(default=50)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_detail', models.ForeignKey(blank=True, to='hallbookingapp.HallDetail', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallSpecialAnnouncement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('announcement', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=80, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_location', models.ForeignKey(blank=True, to='hallbookingapp.HallLocation', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('year', models.IntegerField(null=True, blank=True)),
                ('holiday_date', models.DateField(null=True, blank=True)),
                ('holiday_date_to', models.DateField(null=True, blank=True)),
                ('holiday_status', models.IntegerField(default=8, choices=[(0, b'Active'), (1, b'Inactive'), (2, b'Deleted')])),
                ('holiday_type', models.IntegerField(default=0, choices=[(0, b'MCCIA Holiday'), (1, b'National Holiday')])),
                ('is_booking_available', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('hall_detail', models.ForeignKey(blank=True, to='hallbookingapp.HallDetail', null=True)),
                ('hall_location', models.ForeignKey(blank=True, to='hallbookingapp.HallLocation', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackDepositDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('deposit_remark', models.CharField(max_length=250, null=True, blank=True)),
                ('cheque_no', models.CharField(max_length=10, null=True, blank=True)),
                ('cheque_date', models.DateField(null=True, blank=True)),
                ('bank_name', models.CharField(max_length=30, null=True, blank=True)),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('company', models.CharField(max_length=200, null=True, blank=True)),
                ('contact_person', models.CharField(max_length=70, null=True, blank=True)),
                ('designation', models.CharField(max_length=50, null=True, blank=True)),
                ('mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_r', models.CharField(max_length=50, null=True, blank=True)),
                ('tel_o', models.CharField(max_length=50, null=True, blank=True)),
                ('email', models.CharField(max_length=90, null=True, blank=True)),
                ('gst', models.CharField(max_length=50, null=True, blank=True)),
                ('deposit_available', models.DecimalField(default=0, null=True, max_digits=12, decimal_places=2, blank=True)),
                ('deposit_status', models.IntegerField(default=0, null=True, blank=True, choices=[(0, b'Retained'), (1, b'Refund')])),
                ('deposit_remark', models.CharField(max_length=250, null=True, blank=True)),
                ('refund_status', models.IntegerField(default=0, null=True, blank=True, choices=[(0, b'Not Initiated'), (1, b'Initiated'), (2, b'Refunded')])),
                ('created_by', models.CharField(max_length=80, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=80, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_blacklisted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('blacklist_remark', models.CharField(max_length=250, null=True, blank=True)),
                ('blacklisted_date', models.DateField(null=True, blank=True)),
                ('blacklisted_by', models.CharField(max_length=80, null=True, blank=True)),
                ('reactivated_date', models.DateField(null=True, blank=True)),
                ('reactivated_remark', models.CharField(max_length=250, null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('member', models.ForeignKey(blank=True, to='membershipapp.UserDetail', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usertrackdepositdetail',
            name='user_track',
            field=models.ForeignKey(blank=True, to='hallbookingapp.UserTrackDetail', null=True),
        ),
        migrations.AddField(
            model_name='hallinterest',
            name='hall_location',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallLocation', null=True),
        ),
        migrations.AddField(
            model_name='hallequipment',
            name='hall_functioning_equipment',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallFunctioningEquipment', null=True),
        ),
        migrations.AddField(
            model_name='halldetail',
            name='hall_equipment',
            field=models.ManyToManyField(to='hallbookingapp.HallFunctioningEquipment'),
        ),
        migrations.AddField(
            model_name='halldetail',
            name='hall_location',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallLocation', null=True),
        ),
        migrations.AddField(
            model_name='hallcheckavailability',
            name='hall_detail',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallDetail', null=True),
        ),
        migrations.AddField(
            model_name='hallbookingdetail',
            name='hall_detail',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallDetail', null=True),
        ),
        migrations.AddField(
            model_name='hallbookingdetail',
            name='hall_location',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallLocation', null=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='user_track',
            field=models.ForeignKey(blank=True, to='hallbookingapp.UserTrackDetail', null=True),
        ),
        migrations.AddField(
            model_name='hall_booking_detail',
            name='Hallbooking_company_detail',
            field=models.ForeignKey(blank=True, to='hallbookingapp.Hallbooking_company_detail', null=True),
        ),
        migrations.AddField(
            model_name='hall_booking_detail',
            name='hall_detail',
            field=models.ForeignKey(blank=True, to='adminapp.Hall_detail_list', null=True),
        ),
        migrations.AddField(
            model_name='hall_booking_detail',
            name='hall_pricing',
            field=models.ForeignKey(blank=True, to='adminapp.Hall_pricing', null=True),
        ),
        migrations.AddField(
            model_name='bookingdetailhistory',
            name='hall_booking_detail',
            field=models.ForeignKey(blank=True, to='hallbookingapp.HallBookingDetail', null=True),
        ),
    ]
