# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hallbookingapp', '0001_initial'),
        ('membershipapp', '0001_initial'),
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPaymentTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('transaction_id', models.CharField(max_length=50, null=True, blank=True)),
                ('reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('payment_for', models.IntegerField(default=3, choices=[(1, b'Membership'), (2, b'Hall Booking'), (3, b'Event'), (0, b'None')])),
                ('payment_mode', models.IntegerField(default=1, choices=[(1, b'Online'), (2, b'UPI'), (3, b'Card'), (4, b'Wallet'), (5, b'IMPS'), (6, b'Cash Cards'), (7, b'MIVSA'), (8, b'Debit Pin'), (9, b'EMI Banks'), (0, b'None')])),
                ('payment_status', models.IntegerField(default=6, choices=[(0, b'Inprogress'), (1, b'Success'), (2, b'Initiated'), (3, b'Failed'), (4, b'Aborted'), (5, b'Pending'), (6, b'Not Paid')])),
                ('merchant_id', models.CharField(max_length=20, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=20, null=True, blank=True)),
                ('consumer_name', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('consumer_email', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_status', models.CharField(max_length=10, null=True, blank=True)),
                ('txn_msg', models.TextField(null=True, blank=True)),
                ('txn_err_msg', models.TextField(null=True, blank=True)),
                ('clnt_txn_ref', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_bank_cd', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_txn_id', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('clnt_rqst_meta', models.TextField(null=True, blank=True)),
                ('tpsl_txn_time', models.CharField(max_length=100, null=True, blank=True)),
                ('bal_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('card_id', models.CharField(max_length=100, null=True, blank=True)),
                ('alias_name', models.CharField(max_length=100, null=True, blank=True)),
                ('bank_transaction_id', models.CharField(max_length=100, null=True, blank=True)),
                ('mandate_reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_hash_matched', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('event_reg', models.ForeignKey(blank=True, to='eventsapp.EventRegistration', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallPaymentTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('transaction_id', models.CharField(max_length=50, null=True, blank=True)),
                ('reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('payment_for', models.IntegerField(default=2, choices=[(1, b'Membership'), (2, b'Hall Booking'), (3, b'Event'), (0, b'None')])),
                ('payment_mode', models.IntegerField(default=1, choices=[(1, b'Online'), (2, b'UPI'), (3, b'Card'), (4, b'Wallet'), (5, b'IMPS'), (6, b'Cash Cards'), (7, b'MIVSA'), (8, b'Debit Pin'), (9, b'EMI Banks'), (0, b'None')])),
                ('payment_status', models.IntegerField(default=6, choices=[(0, b'Inprogress'), (1, b'Success'), (2, b'Initiated'), (3, b'Failed'), (4, b'Aborted'), (5, b'Pending'), (6, b'Not Paid')])),
                ('merchant_id', models.CharField(max_length=20, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=20, null=True, blank=True)),
                ('consumer_name', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('consumer_email', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_status', models.CharField(max_length=10, null=True, blank=True)),
                ('txn_msg', models.TextField(null=True, blank=True)),
                ('txn_err_msg', models.TextField(null=True, blank=True)),
                ('clnt_txn_ref', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_bank_cd', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_txn_id', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('clnt_rqst_meta', models.TextField(null=True, blank=True)),
                ('tpsl_txn_time', models.CharField(max_length=100, null=True, blank=True)),
                ('bal_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('card_id', models.CharField(max_length=100, null=True, blank=True)),
                ('alias_name', models.CharField(max_length=100, null=True, blank=True)),
                ('bank_transaction_id', models.CharField(max_length=100, null=True, blank=True)),
                ('mandate_reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_hash_matched', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('hall_booking', models.ForeignKey(blank=True, to='hallbookingapp.HallBooking', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPaymentTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('transaction_id', models.CharField(max_length=50, null=True, blank=True)),
                ('reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('payment_for', models.IntegerField(default=1, choices=[(1, b'Membership'), (2, b'Hall Booking'), (3, b'Event'), (0, b'None')])),
                ('payment_mode', models.IntegerField(default=0, choices=[(1, b'Online'), (2, b'UPI'), (3, b'Card'), (4, b'Wallet'), (5, b'IMPS'), (6, b'Cash Cards'), (7, b'MIVSA'), (8, b'Debit Pin'), (9, b'EMI Banks'), (0, b'None')])),
                ('payment_status', models.IntegerField(default=6, choices=[(0, b'Inprogress'), (1, b'Success'), (2, b'Initiated'), (3, b'Failed'), (4, b'Aborted'), (5, b'Pending'), (6, b'Not Paid')])),
                ('merchant_id', models.CharField(max_length=20, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=20, null=True, blank=True)),
                ('consumer_name', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('consumer_email', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_status', models.CharField(max_length=10, null=True, blank=True)),
                ('txn_msg', models.TextField(null=True, blank=True)),
                ('txn_err_msg', models.TextField(null=True, blank=True)),
                ('clnt_txn_ref', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_bank_cd', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_txn_id', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('clnt_rqst_meta', models.TextField(null=True, blank=True)),
                ('tpsl_txn_time', models.CharField(max_length=100, null=True, blank=True)),
                ('bal_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('card_id', models.CharField(max_length=100, null=True, blank=True)),
                ('alias_name', models.CharField(max_length=100, null=True, blank=True)),
                ('bank_transaction_id', models.CharField(max_length=100, null=True, blank=True)),
                ('mandate_reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_hash_matched', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_renew', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('membership_invoice', models.ForeignKey(blank=True, to='membershipapp.MembershipInvoice', null=True)),
                ('payment_detail', models.ForeignKey(blank=True, to='membershipapp.PaymentDetails', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('transaction_id', models.CharField(max_length=50, null=True, blank=True)),
                ('reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('payment_for', models.IntegerField(default=0, choices=[(1, b'Membership'), (2, b'Hall Booking'), (3, b'Event'), (0, b'None')])),
                ('payment_mode', models.IntegerField(default=0, choices=[(1, b'Online'), (2, b'UPI'), (3, b'Card'), (4, b'Wallet'), (5, b'IMPS'), (6, b'Cash Cards'), (7, b'MIVSA'), (8, b'Debit Pin'), (9, b'EMI Banks'), (0, b'None')])),
                ('merchant_id', models.CharField(max_length=20, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=20, null=True, blank=True)),
                ('consumer_name', models.CharField(max_length=100, null=True, blank=True)),
                ('consumer_mobile_no', models.CharField(max_length=50, null=True, blank=True)),
                ('consumer_email', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_status', models.CharField(max_length=10, null=True, blank=True)),
                ('txn_msg', models.TextField(null=True, blank=True)),
                ('txn_err_msg', models.TextField(null=True, blank=True)),
                ('clnt_txn_ref', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_bank_cd', models.CharField(max_length=100, null=True, blank=True)),
                ('tpsl_txn_id', models.CharField(max_length=100, null=True, blank=True)),
                ('txn_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('clnt_rqst_meta', models.TextField(null=True, blank=True)),
                ('tpsl_txn_time', models.CharField(max_length=100, null=True, blank=True)),
                ('bal_amt', models.CharField(max_length=100, null=True, blank=True)),
                ('card_id', models.CharField(max_length=100, null=True, blank=True)),
                ('alias_name', models.CharField(max_length=100, null=True, blank=True)),
                ('bank_transaction_id', models.CharField(max_length=100, null=True, blank=True)),
                ('mandate_reg_no', models.CharField(max_length=100, null=True, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('is_hash_matched', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('txn_status', models.IntegerField(default=0, choices=[(0, b'Inprogress'), (1, b'Success'), (2, b'Initiated'), (3, b'Failed'), (4, b'Aborted')])),
                ('payment_status', models.IntegerField(default=5, choices=[(0, b'Inprogress'), (1, b'Success'), (2, b'Initiated'), (3, b'Failed'), (4, b'Aborted'), (5, b'Pending'), (6, b'Not Paid')])),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('payment_transaction', models.ForeignKey(blank=True, to='Paymentapp.PaymentTransaction', null=True)),
            ],
        ),
    ]
