# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('city_name', models.CharField(default=None, max_length=50)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('committee', models.CharField(max_length=150, blank=True)),
                ('chairman1_name', models.CharField(max_length=150, blank=True)),
                ('chairman1_company', models.CharField(max_length=150, blank=True)),
                ('chairman1_designation', models.CharField(max_length=150, blank=True)),
                ('chairman1_address', models.CharField(max_length=300, blank=True)),
                ('chairman1_email', models.CharField(max_length=150, blank=True)),
                ('chairman1_mobile', models.CharField(max_length=35, blank=True)),
                ('chairman1_telephone', models.CharField(max_length=35, blank=True)),
                ('chairman1_profile_link', models.CharField(max_length=250, blank=True)),
                ('chairman2_name', models.CharField(max_length=150, blank=True)),
                ('chairman2_company', models.CharField(max_length=150, blank=True)),
                ('chairman2_designation', models.CharField(max_length=150, blank=True)),
                ('chairman2_address', models.CharField(max_length=300, blank=True)),
                ('chairman2_email', models.CharField(max_length=150, blank=True)),
                ('chairman2_mobile', models.CharField(max_length=35, blank=True)),
                ('chairman2_telephone', models.CharField(max_length=35, blank=True)),
                ('chairman2_profile_link', models.CharField(max_length=250, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('contact_person1', models.ForeignKey(related_name='committee_contact_person1', blank=True, to='backofficeapp.SystemUserProfile', null=True)),
                ('contact_person2', models.ForeignKey(related_name='committee_contact_person2', blank=True, to='backofficeapp.SystemUserProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('country_name', models.CharField(max_length=50, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Hall_detail_list',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hall_name', models.CharField(max_length=40, blank=True)),
                ('hall_address', models.CharField(max_length=100, blank=True)),
                ('capacity', models.IntegerField(default=50)),
                ('seating_style', models.CharField(max_length=20, blank=True)),
                ('amenities', models.CharField(max_length=150, blank=True)),
                ('hall_image', models.ImageField(null=True, upload_to=b'HallImage', blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('city', models.ForeignKey(blank=True, to='adminapp.City', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall_Functioning_Equipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('equipment_name', models.CharField(max_length=300)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Hall_pricing',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hours', models.CharField(max_length=10, blank=True)),
                ('eight_member_price', models.IntegerField(default=50)),
                ('eight_nonmember_price', models.IntegerField(default=50)),
                ('four_member_price', models.IntegerField(default=50)),
                ('four_nonmember_price', models.IntegerField(default=50)),
                ('two_member_price', models.IntegerField(default=50)),
                ('two_nonmember_price', models.IntegerField(default=50)),
                ('deposit_holiday', models.IntegerField(default=50)),
                ('deposit_working', models.IntegerField(default=50)),
                ('extra_hour', models.CharField(max_length=10, blank=True)),
                ('extra_member_price', models.IntegerField(default=50)),
                ('extra_nonmember_price', models.IntegerField(default=50)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('hall_detail', models.ForeignKey(blank=True, to='adminapp.Hall_detail_list', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryDescription',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('previous_id', models.CharField(max_length=100, blank=True)),
                ('code', models.CharField(max_length=100, blank=True)),
                ('description', models.CharField(max_length=150, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('previous_id', models.CharField(max_length=100, blank=True)),
                ('code', models.CharField(max_length=100, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('location', models.CharField(max_length=100, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('city', models.ForeignKey(blank=True, to='adminapp.City', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('enroll_type', models.CharField(max_length=150, null=True, blank=True)),
                ('category_enroll_type', models.CharField(max_length=150, null=True, blank=True)),
                ('membership_code', models.CharField(max_length=150, blank=True)),
                ('membership_category', models.CharField(max_length=150, blank=True)),
                ('membership_type', models.CharField(max_length=150, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDescription',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('previous_id', models.CharField(max_length=100, blank=True)),
                ('membership_description', models.CharField(max_length=150, blank=True)),
                ('code', models.CharField(max_length=20, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=10, blank=True)),
                ('description', models.CharField(max_length=150, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='MembershipSlab',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=100, null=True, blank=True)),
                ('slab', models.CharField(max_length=150, null=True, blank=True)),
                ('enroll_type', models.CharField(max_length=150, null=True, blank=True)),
                ('slab_type', models.CharField(max_length=150, null=True, blank=True)),
                ('applicableTo', models.CharField(default=b'Associates', max_length=15, choices=[(b'Associates', b'Associates'), (b'Members', b'Members'), (b'Individual', b'Individual')])),
                ('annual_fee', models.CharField(max_length=150, null=True, blank=True)),
                ('entrance_fee', models.CharField(max_length=150, null=True, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='NameSign',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=70, null=True, blank=True)),
                ('sign', models.FileField(null=True, upload_to=b'SignFolder', blank=True)),
                ('designation', models.IntegerField(default=0, choices=[(0, b'President'), (1, b'Director General')])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('updated_by', models.CharField(max_length=50, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicetax',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.CharField(default=10, max_length=20, blank=True)),
                ('tax', models.CharField(max_length=20, blank=True)),
                ('cgst', models.CharField(max_length=20, blank=True)),
                ('sgst', models.CharField(max_length=20, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('tax_type', models.IntegerField(default=0, choices=[(0, b'GST'), (1, b'IGST')])),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='SlabCriteria',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slab_criteria', models.CharField(max_length=150, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state_name', models.CharField(max_length=50, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True, choices=[(True, True), (False, False)])),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('country', models.ForeignKey(blank=True, to='adminapp.Country', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('task_force', models.CharField(max_length=150, blank=True)),
                ('created_by', models.CharField(max_length=100, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.AddField(
            model_name='membershipslab',
            name='cr3',
            field=models.ForeignKey(blank=True, to='adminapp.SlabCriteria', null=True),
        ),
        migrations.AddField(
            model_name='membershipslab',
            name='membershipCategory',
            field=models.ForeignKey(blank=True, to='adminapp.MembershipCategory', null=True),
        ),
        migrations.AddField(
            model_name='hall_detail_list',
            name='hall_equipment',
            field=models.ManyToManyField(to='adminapp.Hall_Functioning_Equipment'),
        ),
        migrations.AddField(
            model_name='hall_detail_list',
            name='location',
            field=models.ForeignKey(blank=True, to='adminapp.Location', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='task_force',
            field=models.ForeignKey(blank=True, to='adminapp.TaskForce', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, to='adminapp.State', null=True),
        ),
    ]
